# Generated by Django 4.1.7 on 2023-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
