# Generated by Django 4.1.7 on 2023-03-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0001_intital.py'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='summary',
        ),
    ]
