# Generated by Django 4.1.7 on 2023-03-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0002_remove_server_owner_remove_server_serverid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(blank=True, to='socialDist.comment'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, to='socialDist.like'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='requests',
            field=models.ManyToManyField(blank=True, to='socialDist.followrequest'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='socialDist.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.TextField(choices=[('text/plain', 'plaintext'), ('text/markdown', 'markdown'), ('application/base64', 'binary'), ('image/png;base64', 'PNG image'), ('image/jpeg;base64', 'JPEG image'), ('image/jpg;base64', 'JPG image')]),
        ),
    ]
