# Generated by Django 4.1.7 on 2023-03-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0002_alter_connection_apicreds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='inboxID',
            field=models.CharField(default='', max_length=80, primary_key=True, serialize=False),
        ),
    ]
