# Generated by Django 4.1.7 on 2023-03-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0002_remove_server_owner_remove_server_serverid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(null=True),
        ),
    ]
