# Generated by Django 4.1.7 on 2023-03-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0003_inbox_comments_inbox_likes_inbox_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_requests', to='socialDist.author'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievced_requests', to='socialDist.author'),
        ),
    ]
