# Generated by Django 4.1.7 on 2023-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0004_alter_author_github_alter_author_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='serverKey',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(),
        ),
    ]
