# Generated by Django 4.1.7 on 2023-03-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0006_alter_author_github_alter_author_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='isLocalServer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
