# Generated by Django 4.1.7 on 2023-03-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0007_server_islocalserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='serverKey',
            field=models.TextField(blank=True),
        ),
    ]
