# Generated by Django 4.1.7 on 2023-03-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0008_alter_server_serverkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('apiAddress', models.URLField(primary_key=True, serialize=False)),
                ('apiCreds', models.TextField()),
            ],
        ),
    ]
