# Generated by Django 4.1.7 on 2023-03-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0009_connection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='ExternalServer',
        ),
    ]
