# Generated by Django 4.1.7 on 2023-03-01 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "authorId",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("displayName", models.CharField(default="", max_length=40)),
                ("github", models.TextField()),
                ("profileImage", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("published", models.DateField(auto_created=True)),
                (
                    "commentID",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("contentType", models.TextField()),
                ("isLiked", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="socialDist.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "serverID",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("serverName", models.CharField(max_length=50)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialDist.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "postID",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=50)),
                ("origin", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("contentType", models.TextField()),
                ("categories", models.CharField(max_length=100)),
                ("count", models.IntegerField()),
                ("published", models.DateField()),
                ("visibility", models.CharField(max_length=30)),
                ("unlisted", models.BooleanField()),
                ("isLiked", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="socialDist.author",
                    ),
                ),
                (
                    "inServer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="socialDist.server",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("dateTime", models.DateTimeField(auto_created=True)),
                (
                    "likeID",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("summary", models.TextField()),
                ("likeType", models.CharField(max_length=20)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked",
                        to="socialDist.author",
                    ),
                ),
                (
                    "parentComment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="socialDist.comment",
                    ),
                ),
                (
                    "parentPost",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="socialDist.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "inboxID",
                    models.CharField(
                        default="", max_length=40, primary_key=True, serialize=False
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialDist.author",
                    ),
                ),
                ("post", models.ManyToManyField(to="socialDist.post")),
            ],
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recievced_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="parentPostID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="socialDist.post",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="inServer",
            field=models.ForeignKey(
                blank="True",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialDist.server",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="isFriendWith",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialDist.author",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="UserFollowing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "following_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user_id", "following_user_id")},},
        ),
    ]
