# Generated by Django 3.1.6 on 2023-02-11 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.TextField()),
                ('profileImg', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('contentType', models.TextField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDist.author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.BinaryField()),
                ('contentType', models.TextField()),
                ('date', models.DateField()),
                ('visibility', models.CharField(max_length=30)),
                ('unlisted', models.BooleanField()),
                ('posterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDist.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('likeType', models.CharField(max_length=20)),
                ('parentComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialDist.comment')),
                ('parentPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialDist.post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='parentPostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDist.post'),
        ),
    ]
