# Generated by Django 4.1.7 on 2023-02-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="isAuthenticated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="author",
            name="isFriendWith",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialDist.author",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="isServerAdmin",
            field=models.BooleanField(default=False),
        ),
    ]
