# Generated by Django 3.1.6 on 2023-03-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='inServer',
        ),
        migrations.RemoveField(
            model_name='author',
            name='isFriendWith',
        ),
    ]
