# Generated by Django 3.1.6 on 2023-02-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='inServer',
        ),
    ]
