# Generated by Django 4.1.7 on 2023-02-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0002_author_isauthenticated_author_isfriendwith_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                ("serverID", models.Field(primary_key=True, serialize=False)),
                ("serverName", models.CharField(max_length=50)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialDist.author",
                    ),
                ),
            ],
        ),
    ]
