# Generated by Django 3.1.6 on 2023-02-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0003_auto_20230221_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeable',
            name='inboxitem_ptr',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likeable_ptr',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='inboxitem_ptr',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='content',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='items',
        ),
        migrations.RemoveField(
            model_name='like',
            name='inboxitem_ptr',
        ),
        migrations.RemoveField(
            model_name='like',
            name='targetObject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likeable_ptr',
        ),
        migrations.AddField(
            model_name='comment',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbox',
            name='post',
            field=models.ManyToManyField(to='socialDist.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='parentComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDist.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='parentPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDist.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inbox', serialize=False, to='socialDist.author'),
        ),
        migrations.DeleteModel(
            name='InboxItem',
        ),
        migrations.DeleteModel(
            name='Likeable',
        ),
    ]
