# Generated by Django 4.1.7 on 2023-02-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0003_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="inServer",
            field=models.ForeignKey(
                blank="True",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialDist.server",
            ),
        ),
    ]
