# Generated by Django 3.1.6 on 2023-03-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0003_auto_20230228_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDist.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='parentPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialDist.post'),
        ),
    ]
