# Generated by Django 4.1.7 on 2023-02-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0004_author_inserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="isLiked", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="server",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="socialDist.server",
            ),
        ),
    ]
