# Generated by Django 4.1.7 on 2023-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0005_post_isliked_post_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="isLiked",
            field=models.BooleanField(default=False),
        ),
    ]
