# Generated by Django 3.1.6 on 2023-03-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0006_auto_20230228_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
