# Generated by Django 4.1.7 on 2023-02-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0006_comment_isliked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("contentType", models.TextField()),
                ("comment", models.ManyToManyField(to="socialDist.comment")),
                ("like", models.ManyToManyField(to="socialDist.like")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialDist.author",
                    ),
                ),
                ("post", models.ManyToManyField(to="socialDist.post")),
            ],
        ),
    ]
