# Generated by Django 3.1.6 on 2023-03-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0008_auto_20230228_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(max_length=100),
        ),
    ]
