# Generated by Django 3.1.6 on 2023-03-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0012_auto_20230301_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='post',
        ),
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(to='socialDist.Post'),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
