# Generated by Django 4.1.7 on 2023-03-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialDist", "0012_auto_20230301_1025"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inbox",
            old_name="post",
            new_name="posts",
        ),
    ]
