# Generated by Django 3.1.6 on 2023-03-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0013_auto_20230302_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likeID',
            new_name='id',
        ),
    ]
