# Generated by Django 3.1.6 on 2023-03-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0014_auto_20230302_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.BinaryField(default=b"helloworld"),
            preserve_default=False,
        ),
    ]
