# Generated by Django 3.1.6 on 2023-03-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0015_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
