# Generated by Django 3.1.6 on 2023-03-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0016_auto_20230302_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Public', 'VISIBLE'), ('Private', 'PRIVATE')], max_length=30),
        ),
    ]
