# Generated by Django 3.1.6 on 2023-03-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDist', '0017_auto_20230302_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('VISIBLE', 'Public'), ('PRIVATE', 'Private')], max_length=30),
        ),
    ]
